-- Seed Harvest History Data (Accurate & Dynamic)
-- Generates realistic 'harvest' table records based on Baglet Status and Harvest Count.
-- Works with dynamic batch IDs generated by seed_harvest_test.sql

-- 1. Clean up existing harvests for ALL test batches (Pattern FPR-YYYYMMDD-Bxxx)
-- We identify test batches by the pattern used in seed_harvest_test.
DELETE FROM harvest 
WHERE batch_id LIKE 'FPR-%-B%' AND batch_id <> 'FPR-REAL-BATCH'; -- Safety check

-- 2. Insert Harvests
INSERT INTO harvest (baglet_id, batch_id, harvest_weight_g, harvested_timestamp, notes, logged_by)
SELECT 
  b.baglet_id,
  b.batch_id,
  -- Realistic Weights based on Flush Sequence
  CASE seq
    WHEN 1 THEN (280 + random() * 60)::numeric(10,2) -- ~310g
    WHEN 2 THEN (180 + random() * 50)::numeric(10,2) -- ~205g
    ELSE (120 + random() * 40)::numeric(10,2)        -- ~140g
  END as harvest_weight_g,
  
  -- Realistic Timestamps relative to BATCH PREPARED DATE
  -- Prep + 21 days (incubate) + (seq-1)*14 days (flush interval) + random jitter
  (bat.prepared_date + INTERVAL '21 days' + ((seq - 1) * INTERVAL '14 days') + (random() * 5 * INTERVAL '1 day')) as harvested_timestamp,
  
  -- Notes
  CASE seq
    WHEN 1 THEN 'First Flush - Good quality'
    WHEN 2 THEN 'Second Flush - Standard'
    ELSE 'Later Flush - Smaller fruits'
  END as notes,
  'tester'
FROM baglet b
JOIN batch bat ON b.batch_id = bat.batch_id
CROSS JOIN generate_series(1, b.harvest_count) as seq
WHERE b.batch_id LIKE 'FPR-%-B%'
  AND b.harvest_count > 0;

-- 3. FORCE EQUAL DISTRIBUTION (Safe & Unique)
-- We distribute harvests across 6 months.
-- To prevent "same baglet, same day" unique constraint violation:
-- We include the harvest sequence in the day calculation.
WITH numbered_harvests AS (
  SELECT 
    harvest_id, 
    baglet_id,
    -- Get flush number (1st, 2nd, 3rd harvest for this bag)
    ROW_NUMBER() OVER (PARTITION BY baglet_id ORDER BY harvest_id) as flush_seq,
    -- Global counter for round-robin month distribution
    ROW_NUMBER() OVER (ORDER BY harvest_id) as global_rn
  FROM harvest 
  WHERE batch_id LIKE 'FPR-%-B%'
)
UPDATE harvest h
SET harvested_timestamp = 
  now_ist()
  -- Month Distribution: 0..5 months ago (Round Robin)
  - (((nh.global_rn % 6)) || ' months')::interval 
  -- Day Of Month: FORCE different days for different flushes.
  -- This guarantees (Baglet, Date) is unique regardless of which Month it falls in.
  + ((nh.flush_seq) || ' days')::interval
FROM numbered_harvests nh
WHERE h.harvest_id = nh.harvest_id;
